#ifndef LANG_LIMITS_H
#define LANG_LIMITS_H

#define LANG_MAX_INDENT_DEPTH 32
#define LANG_MAX_IDENTIFIER_LEN 63
#define LANG_MAX_STRING_LITERAL_LEN 4095

#define LANG_MAX_ENUM_MEMBERS 1024
#define LANG_MAX_ENUM_FIELDS 256

#endif /* _H */
