#ifndef PARSER_LIMITS_H
#define PARSER_LIMITS_H

#define PARSER_MAX_INDENT_DEPTH 128
#define PARSER_MAX_IDENTIFIER_LENGTH 127
#define PARSER_MAX_STRING_LITERAL_LENGTH 4095

#define LANG_MAX_ENUM_MEMBERS 1024
#define LANG_MAX_ENUM_FIELDS 256

#endif /* _H */
